name: restate
description: "A Flutter Real Estate project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/fonts/

  fonts:
    - family: Euclid-Circular
      fonts:
        - asset: assets/fonts/Euclid-Circular-Light.ttf
          weight: 300
        - asset: assets/fonts/Euclid-Circular-Light-Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Euclid-Circular-Regular.ttf
          weight: 400
        - asset: assets/fonts/Euclid-Circular-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Euclid-Circular-Medium.ttf
          weight: 500
        - asset: assets/fonts/Euclid-Circular-Medium-Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Euclid-Circular-Bold.ttf
          weight: 700
        - asset: assets/fonts/Euclid-Circular-Bold-Italic.ttf
          weight: 700
          style: italic
